events {}

http {
  server {
    listen 80;

    location / {
      if ($request_method !~ ^(GET|HEAD|OPTIONS)$) {
        return 403 "registry is read-only on this port\n";
      }

      proxy_pass http://apicurio-registry:8080;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}
